title: My tipitaka notes
description: bla bla bla
theme: just-the-docs

url: https://yukach.github.io/tipitaka-by

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
